# Generated by Django 6.1.1 on 2026-10-09 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('post_view', 'Post View'), ('reaction', 'Reaction'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('follow', 'Follow'), ('post_published', 'Post Published')], db_index=True, max_length=30)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='blog.post')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='analytics_a_event_t_69a889_idx'), models.Index(fields=['post', 'occurred_at'], name='analytics_a_post_id_ee7528_idx'), models.Index(fields=['actor', 'occurred_at'], name='analytics_a_actor_i_042d88_idx')],
            },
        ),
    ]
