# Generated by Django 6.1.1 on 2026-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_review_notes_post_reviewed_at_post_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
