# Generated by Django 6.1.1 on 2026-09-22 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('insightful', 'Insightful'), ('helpful', 'Helpful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post'], name='engagements_post_id_6151ce_idx'), models.Index(fields=['user'], name='engagements_user_id_dfd7ca_idx'), models.Index(fields=['reaction_type'], name='engagements_reactio_bc0e57_idx'), models.Index(fields=['post', 'reaction_type'], name='engagements_post_id_89ce0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_reaction')],
            },
        ),
    ]
