# Generated by Django 6.1.1 on 2026-10-02 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='engagements_user_id_33d560_idx'), models.Index(fields=['post'], name='engagements_post_id_a0d70b_idx'), models.Index(fields=['created_at'], name='engagements_created_ac9c5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_bookmark')],
            },
        ),
    ]
