# Generated by Django 6.1.1 on 2026-10-02 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
        ('engagements', '0002_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='engagements_user_id_86a37a_idx'), models.Index(fields=['post'], name='engagements_post_id_dd4e43_idx'), models.Index(fields=['platform'], name='engagements_platfor_7c029e_idx'), models.Index(fields=['created_at'], name='engagements_created_2c4ac7_idx'), models.Index(fields=['post', 'platform'], name='engagements_post_id_dc1d01_idx')],
            },
        ),
    ]
