# Generated by Django 6.1.1 on 2026-10-07 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower'], name='engagements_followe_e9eda7_idx'), models.Index(fields=['following'], name='engagements_followi_d47fe4_idx'), models.Index(fields=['created_at'], name='engagements_created_b33c6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follower_following')],
            },
        ),
    ]
